apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-bot
  name: argocd-bot
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-bot
